name: main
on: [push]
jobs:
  Build-Test-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Tests
        run: |
          npm install --include=dev
          npm test
      - name: Docker Login
        env: 
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Docker Build
        run: |
          docker build -f ./ -t mmullin12/front-end-skeleton .
      - name: Docker Push
        run: |
          docker push mmullin12/front-end-skeleton