name: main
on: [push]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Unit Tests
        run: |
          npm install --dev
          npm test