name: main
on: [push]
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v4
      - name: Unit Tests
        run: npm test
      - name: Docker build
        run: echo build