name: main
on: [push]
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker step
        uses: ./.github/actions/test/
        id: tests