name: main
on: [push]
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - uses: actions/checkout@v4
      - name: Run Docker Container
        uses: ./.github/actions/test/